/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class Avatar : AvatarBase)
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Avatar.def
	// Please inherit and implement "class Avatar : AvatarBase"
	public abstract class AvatarBase : Entity
	{
		public EntityBaseEntityCall_AvatarBase baseEntityCall = null;
		public EntityCellEntityCall_AvatarBase cellEntityCall = null;

		public Byte CrystalAvaliable = 0;
		public virtual void onCrystalAvaliableChanged(Byte oldValue) {}
		public Byte CrystalSum = 0;
		public virtual void onCrystalSumChanged(Byte oldValue) {}
		public string NameA = "";
		public virtual void onNameAChanged(string oldValue) {}
		public Byte RoleType = 0;
		public virtual void onRoleTypeChanged(Byte oldValue) {}
		public Byte Situation = 0;
		public virtual void onSituationChanged(Byte oldValue) {}


		public AvatarBase()
		{
		}

		public override void onGetBase()
		{
			baseEntityCall = new EntityBaseEntityCall_AvatarBase(id, className);
		}

		public override void onGetCell()
		{
			cellEntityCall = new EntityCellEntityCall_AvatarBase(id, className);
		}

		public override void onLoseCell()
		{
			cellEntityCall = null;
		}

		public override EntityCall getBaseEntityCall()
		{
			return baseEntityCall;
		}

		public override EntityCall getCellEntityCall()
		{
			return cellEntityCall;
		}

		public override void onRemoteMethodCall(MemoryStream stream)
		{
			ScriptModule sm = EntityDef.moduledefs["Avatar"];

			UInt16 methodUtype = 0;
			UInt16 componentPropertyUType = 0;

			if(sm.useMethodDescrAlias)
			{
				componentPropertyUType = stream.readUint8();
				methodUtype = stream.readUint8();
			}
			else
			{
				componentPropertyUType = stream.readUint16();
				methodUtype = stream.readUint16();
			}

			Method method = null;

			if(componentPropertyUType == 0)
			{
				method = sm.idmethods[methodUtype];
			}
			else
			{
				Property pComponentPropertyDescription = sm.idpropertys[componentPropertyUType];
				switch(pComponentPropertyDescription.properUtype)
				{
					default:
						break;
				}

				return;
			}

			switch(method.methodUtype)
			{
				default:
					break;
			};
		}

		public override void onUpdatePropertys(MemoryStream stream)
		{
			ScriptModule sm = EntityDef.moduledefs["Avatar"];
			Dictionary<UInt16, Property> pdatas = sm.idpropertys;

			while(stream.length() > 0)
			{
				UInt16 _t_utype = 0;
				UInt16 _t_child_utype = 0;

				{
					if(sm.usePropertyDescrAlias)
					{
						_t_utype = stream.readUint8();
						_t_child_utype = stream.readUint8();
					}
					else
					{
						_t_utype = stream.readUint16();
						_t_child_utype = stream.readUint16();
					}
				}

				Property prop = null;

				if(_t_utype == 0)
				{
					prop = pdatas[_t_child_utype];
				}
				else
				{
					Property pComponentPropertyDescription = pdatas[_t_utype];
					switch(pComponentPropertyDescription.properUtype)
					{
						default:
							break;
					}

					return;
				}

				switch(prop.properUtype)
				{
					case 17:
						Byte oldval_CrystalAvaliable = CrystalAvaliable;
						CrystalAvaliable = stream.readUint8();

						if(prop.isBase())
						{
							if(inited)
								onCrystalAvaliableChanged(oldval_CrystalAvaliable);
						}
						else
						{
							if(inWorld)
								onCrystalAvaliableChanged(oldval_CrystalAvaliable);
						}

						break;
					case 16:
						Byte oldval_CrystalSum = CrystalSum;
						CrystalSum = stream.readUint8();

						if(prop.isBase())
						{
							if(inited)
								onCrystalSumChanged(oldval_CrystalSum);
						}
						else
						{
							if(inWorld)
								onCrystalSumChanged(oldval_CrystalSum);
						}

						break;
					case 11:
						string oldval_NameA = NameA;
						NameA = stream.readUnicode();

						if(prop.isBase())
						{
							if(inited)
								onNameAChanged(oldval_NameA);
						}
						else
						{
							if(inWorld)
								onNameAChanged(oldval_NameA);
						}

						break;
					case 12:
						Byte oldval_RoleType = RoleType;
						RoleType = stream.readUint8();

						if(prop.isBase())
						{
							if(inited)
								onRoleTypeChanged(oldval_RoleType);
						}
						else
						{
							if(inWorld)
								onRoleTypeChanged(oldval_RoleType);
						}

						break;
					case 13:
						Byte oldval_Situation = Situation;
						Situation = stream.readUint8();

						if(prop.isBase())
						{
							if(inited)
								onSituationChanged(oldval_Situation);
						}
						else
						{
							if(inWorld)
								onSituationChanged(oldval_Situation);
						}

						break;
					case 40001:
						Vector3 oldval_direction = direction;
						direction = stream.readVector3();

						if(prop.isBase())
						{
							if(inited)
								onDirectionChanged(oldval_direction);
						}
						else
						{
							if(inWorld)
								onDirectionChanged(oldval_direction);
						}

						break;
					case 40000:
						Vector3 oldval_position = position;
						position = stream.readVector3();

						if(prop.isBase())
						{
							if(inited)
								onPositionChanged(oldval_position);
						}
						else
						{
							if(inWorld)
								onPositionChanged(oldval_position);
						}

						break;
					case 40002:
						stream.readUint32();
						break;
					default:
						break;
				};
			}
		}

		public override void callPropertysSetMethods()
		{
			ScriptModule sm = EntityDef.moduledefs["Avatar"];
			Dictionary<UInt16, Property> pdatas = sm.idpropertys;

			Byte oldval_CrystalAvaliable = CrystalAvaliable;
			Property prop_CrystalAvaliable = pdatas[4];
			if(prop_CrystalAvaliable.isBase())
			{
				if(inited && !inWorld)
					onCrystalAvaliableChanged(oldval_CrystalAvaliable);
			}
			else
			{
				if(inWorld)
				{
					if(prop_CrystalAvaliable.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onCrystalAvaliableChanged(oldval_CrystalAvaliable);
					}
				}
			}

			Byte oldval_CrystalSum = CrystalSum;
			Property prop_CrystalSum = pdatas[5];
			if(prop_CrystalSum.isBase())
			{
				if(inited && !inWorld)
					onCrystalSumChanged(oldval_CrystalSum);
			}
			else
			{
				if(inWorld)
				{
					if(prop_CrystalSum.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onCrystalSumChanged(oldval_CrystalSum);
					}
				}
			}

			string oldval_NameA = NameA;
			Property prop_NameA = pdatas[6];
			if(prop_NameA.isBase())
			{
				if(inited && !inWorld)
					onNameAChanged(oldval_NameA);
			}
			else
			{
				if(inWorld)
				{
					if(prop_NameA.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onNameAChanged(oldval_NameA);
					}
				}
			}

			Byte oldval_RoleType = RoleType;
			Property prop_RoleType = pdatas[7];
			if(prop_RoleType.isBase())
			{
				if(inited && !inWorld)
					onRoleTypeChanged(oldval_RoleType);
			}
			else
			{
				if(inWorld)
				{
					if(prop_RoleType.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onRoleTypeChanged(oldval_RoleType);
					}
				}
			}

			Byte oldval_Situation = Situation;
			Property prop_Situation = pdatas[8];
			if(prop_Situation.isBase())
			{
				if(inited && !inWorld)
					onSituationChanged(oldval_Situation);
			}
			else
			{
				if(inWorld)
				{
					if(prop_Situation.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onSituationChanged(oldval_Situation);
					}
				}
			}

			Vector3 oldval_direction = direction;
			Property prop_direction = pdatas[2];
			if(prop_direction.isBase())
			{
				if(inited && !inWorld)
					onDirectionChanged(oldval_direction);
			}
			else
			{
				if(inWorld)
				{
					if(prop_direction.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onDirectionChanged(oldval_direction);
					}
				}
			}

			Vector3 oldval_position = position;
			Property prop_position = pdatas[1];
			if(prop_position.isBase())
			{
				if(inited && !inWorld)
					onPositionChanged(oldval_position);
			}
			else
			{
				if(inWorld)
				{
					if(prop_position.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onPositionChanged(oldval_position);
					}
				}
			}

		}
	}
}