/*
	Generated by KBEngine!
	Please do not modify this file!
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	public class EntityDef
	{
		public static Dictionary<string, UInt16> datatype2id = new Dictionary<string, UInt16>();
		public static Dictionary<string, DATATYPE_BASE> datatypes = new Dictionary<string, DATATYPE_BASE>();
		public static Dictionary<UInt16, DATATYPE_BASE> id2datatypes = new Dictionary<UInt16, DATATYPE_BASE>();
		public static Dictionary<string, Int32> entityclass = new Dictionary<string, Int32>();
		public static Dictionary<string, ScriptModule> moduledefs = new Dictionary<string, ScriptModule>();
		public static Dictionary<UInt16, ScriptModule> idmoduledefs = new Dictionary<UInt16, ScriptModule>();

		public static bool init()
		{
			initDataTypes();
			initDefTypes();
			initScriptModules();
			return true;
		}

		public static bool reset()
		{
			clear();
			return init();
		}

		public static void clear()
		{
			datatype2id.Clear();
			datatypes.Clear();
			id2datatypes.Clear();
			entityclass.Clear();
			moduledefs.Clear();
			idmoduledefs.Clear();
		}

		public static void initDataTypes()
		{
			datatypes["UINT8"] = new DATATYPE_UINT8();
			datatypes["UINT16"] = new DATATYPE_UINT16();
			datatypes["UINT32"] = new DATATYPE_UINT32();
			datatypes["UINT64"] = new DATATYPE_UINT64();

			datatypes["INT8"] = new DATATYPE_INT8();
			datatypes["INT16"] = new DATATYPE_INT16();
			datatypes["INT32"] = new DATATYPE_INT32();
			datatypes["INT64"] = new DATATYPE_INT64();

			datatypes["FLOAT"] = new DATATYPE_FLOAT();
			datatypes["DOUBLE"] = new DATATYPE_DOUBLE();

			datatypes["STRING"] = new DATATYPE_STRING();
			datatypes["VECTOR2"] = new DATATYPE_VECTOR2();

			datatypes["VECTOR3"] = new DATATYPE_VECTOR3();

			datatypes["VECTOR4"] = new DATATYPE_VECTOR4();
			datatypes["PYTHON"] = new DATATYPE_PYTHON();

			datatypes["UNICODE"] = new DATATYPE_UNICODE();
			datatypes["ENTITYCALL"] = new DATATYPE_ENTITYCALL();

			datatypes["BLOB"] = new DATATYPE_BLOB();
		}

		public static void initScriptModules()
		{
			ScriptModule pAccountModule = new ScriptModule("Account");
			EntityDef.moduledefs["Account"] = pAccountModule;
			EntityDef.idmoduledefs[1] = pAccountModule;

			Property pAccount_position = new Property();
			pAccount_position.name = "position";
			pAccount_position.properUtype = 40000;
			pAccount_position.properFlags = 4;
			pAccount_position.aliasID = 1;
			Vector3 Account_position_defval = new Vector3();
			pAccount_position.defaultVal = Account_position_defval;
			pAccountModule.propertys["position"] = pAccount_position; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_position.aliasID] = pAccount_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(position / 40000).");

			Property pAccount_direction = new Property();
			pAccount_direction.name = "direction";
			pAccount_direction.properUtype = 40001;
			pAccount_direction.properFlags = 4;
			pAccount_direction.aliasID = 2;
			Vector3 Account_direction_defval = new Vector3();
			pAccount_direction.defaultVal = Account_direction_defval;
			pAccountModule.propertys["direction"] = pAccount_direction; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_direction.aliasID] = pAccount_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(direction / 40001).");

			Property pAccount_spaceID = new Property();
			pAccount_spaceID.name = "spaceID";
			pAccount_spaceID.properUtype = 40002;
			pAccount_spaceID.properFlags = 16;
			pAccount_spaceID.aliasID = 3;
			UInt32 Account_spaceID_defval;
			UInt32.TryParse("", out Account_spaceID_defval);
			pAccount_spaceID.defaultVal = Account_spaceID_defval;
			pAccountModule.propertys["spaceID"] = pAccount_spaceID; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_spaceID.aliasID] = pAccount_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(spaceID / 40002).");

			Property pAccount_CardGroupList = new Property();
			pAccount_CardGroupList.name = "CardGroupList";
			pAccount_CardGroupList.properUtype = 6;
			pAccount_CardGroupList.properFlags = 32;
			pAccount_CardGroupList.aliasID = 4;
			pAccount_CardGroupList.defaultVal = EntityDef.id2datatypes[26].parseDefaultValStr("");
			pAccountModule.propertys["CardGroupList"] = pAccount_CardGroupList; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_CardGroupList.aliasID] = pAccount_CardGroupList;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(CardGroupList / 6).");

			Property pAccount_CardList = new Property();
			pAccount_CardList.name = "CardList";
			pAccount_CardList.properUtype = 5;
			pAccount_CardList.properFlags = 32;
			pAccount_CardList.aliasID = 5;
			pAccount_CardList.defaultVal = EntityDef.id2datatypes[24].parseDefaultValStr("");
			pAccountModule.propertys["CardList"] = pAccount_CardList; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_CardList.aliasID] = pAccount_CardList;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(CardList / 5).");

			Property pAccount_Gold = new Property();
			pAccount_Gold.name = "Gold";
			pAccount_Gold.properUtype = 3;
			pAccount_Gold.properFlags = 32;
			pAccount_Gold.aliasID = 6;
			Int32 Account_Gold_defval;
			Int32.TryParse("", out Account_Gold_defval);
			pAccount_Gold.defaultVal = Account_Gold_defval;
			pAccountModule.propertys["Gold"] = pAccount_Gold; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_Gold.aliasID] = pAccount_Gold;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(Gold / 3).");

			Property pAccount_Kabao = new Property();
			pAccount_Kabao.name = "Kabao";
			pAccount_Kabao.properUtype = 4;
			pAccount_Kabao.properFlags = 32;
			pAccount_Kabao.aliasID = 7;
			Int32 Account_Kabao_defval;
			Int32.TryParse("", out Account_Kabao_defval);
			pAccount_Kabao.defaultVal = Account_Kabao_defval;
			pAccountModule.propertys["Kabao"] = pAccount_Kabao; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_Kabao.aliasID] = pAccount_Kabao;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(Kabao / 4).");

			Property pAccount_Level = new Property();
			pAccount_Level.name = "Level";
			pAccount_Level.properUtype = 2;
			pAccount_Level.properFlags = 32;
			pAccount_Level.aliasID = 8;
			Int16 Account_Level_defval;
			Int16.TryParse("", out Account_Level_defval);
			pAccount_Level.defaultVal = Account_Level_defval;
			pAccountModule.propertys["Level"] = pAccount_Level; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_Level.aliasID] = pAccount_Level;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(Level / 2).");

			Property pAccount_Name = new Property();
			pAccount_Name.name = "Name";
			pAccount_Name.properUtype = 1;
			pAccount_Name.properFlags = 32;
			pAccount_Name.aliasID = 9;
			string Account_Name_defval = "";
			pAccount_Name.defaultVal = Account_Name_defval;
			pAccountModule.propertys["Name"] = pAccount_Name; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_Name.aliasID] = pAccount_Name;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(Name / 1).");

			List<DATATYPE_BASE> pAccount_onOpenPack_args = new List<DATATYPE_BASE>();
			pAccount_onOpenPack_args.Add(EntityDef.id2datatypes[23]);

			Method pAccount_onOpenPack = new Method();
			pAccount_onOpenPack.name = "onOpenPack";
			pAccount_onOpenPack.methodUtype = 8;
			pAccount_onOpenPack.aliasID = 1;
			pAccount_onOpenPack.args = pAccount_onOpenPack_args;

			pAccountModule.methods["onOpenPack"] = pAccount_onOpenPack; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_onOpenPack.aliasID] = pAccount_onOpenPack;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(onOpenPack / 8).");

			List<DATATYPE_BASE> pAccount_onReqCardList_args = new List<DATATYPE_BASE>();
			pAccount_onReqCardList_args.Add(EntityDef.id2datatypes[24]);
			pAccount_onReqCardList_args.Add(EntityDef.id2datatypes[26]);

			Method pAccount_onReqCardList = new Method();
			pAccount_onReqCardList.name = "onReqCardList";
			pAccount_onReqCardList.methodUtype = 9;
			pAccount_onReqCardList.aliasID = 2;
			pAccount_onReqCardList.args = pAccount_onReqCardList_args;

			pAccountModule.methods["onReqCardList"] = pAccount_onReqCardList; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_onReqCardList.aliasID] = pAccount_onReqCardList;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(onReqCardList / 9).");

			List<DATATYPE_BASE> pAccount_reqBuyKabao_args = new List<DATATYPE_BASE>();
			pAccount_reqBuyKabao_args.Add(EntityDef.id2datatypes[8]);

			Method pAccount_reqBuyKabao = new Method();
			pAccount_reqBuyKabao.name = "reqBuyKabao";
			pAccount_reqBuyKabao.methodUtype = 3;
			pAccount_reqBuyKabao.aliasID = -1;
			pAccount_reqBuyKabao.args = pAccount_reqBuyKabao_args;

			pAccountModule.methods["reqBuyKabao"] = pAccount_reqBuyKabao; 
			pAccountModule.base_methods["reqBuyKabao"] = pAccount_reqBuyKabao;

			pAccountModule.idbase_methods[pAccount_reqBuyKabao.methodUtype] = pAccount_reqBuyKabao;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqBuyKabao / 3).");

			List<DATATYPE_BASE> pAccount_reqCardList_args = new List<DATATYPE_BASE>();

			Method pAccount_reqCardList = new Method();
			pAccount_reqCardList.name = "reqCardList";
			pAccount_reqCardList.methodUtype = 7;
			pAccount_reqCardList.aliasID = -1;
			pAccount_reqCardList.args = pAccount_reqCardList_args;

			pAccountModule.methods["reqCardList"] = pAccount_reqCardList; 
			pAccountModule.base_methods["reqCardList"] = pAccount_reqCardList;

			pAccountModule.idbase_methods[pAccount_reqCardList.methodUtype] = pAccount_reqCardList;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqCardList / 7).");

			List<DATATYPE_BASE> pAccount_reqChangeLevel_args = new List<DATATYPE_BASE>();
			pAccount_reqChangeLevel_args.Add(EntityDef.id2datatypes[7]);

			Method pAccount_reqChangeLevel = new Method();
			pAccount_reqChangeLevel.name = "reqChangeLevel";
			pAccount_reqChangeLevel.methodUtype = 2;
			pAccount_reqChangeLevel.aliasID = -1;
			pAccount_reqChangeLevel.args = pAccount_reqChangeLevel_args;

			pAccountModule.methods["reqChangeLevel"] = pAccount_reqChangeLevel; 
			pAccountModule.base_methods["reqChangeLevel"] = pAccount_reqChangeLevel;

			pAccountModule.idbase_methods[pAccount_reqChangeLevel.methodUtype] = pAccount_reqChangeLevel;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqChangeLevel / 2).");

			List<DATATYPE_BASE> pAccount_reqChangeName_args = new List<DATATYPE_BASE>();
			pAccount_reqChangeName_args.Add(EntityDef.id2datatypes[12]);

			Method pAccount_reqChangeName = new Method();
			pAccount_reqChangeName.name = "reqChangeName";
			pAccount_reqChangeName.methodUtype = 1;
			pAccount_reqChangeName.aliasID = -1;
			pAccount_reqChangeName.args = pAccount_reqChangeName_args;

			pAccountModule.methods["reqChangeName"] = pAccount_reqChangeName; 
			pAccountModule.base_methods["reqChangeName"] = pAccount_reqChangeName;

			pAccountModule.idbase_methods[pAccount_reqChangeName.methodUtype] = pAccount_reqChangeName;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqChangeName / 1).");

			List<DATATYPE_BASE> pAccount_reqDelCardGroup_args = new List<DATATYPE_BASE>();
			pAccount_reqDelCardGroup_args.Add(EntityDef.id2datatypes[6]);

			Method pAccount_reqDelCardGroup = new Method();
			pAccount_reqDelCardGroup.name = "reqDelCardGroup";
			pAccount_reqDelCardGroup.methodUtype = 6;
			pAccount_reqDelCardGroup.aliasID = -1;
			pAccount_reqDelCardGroup.args = pAccount_reqDelCardGroup_args;

			pAccountModule.methods["reqDelCardGroup"] = pAccount_reqDelCardGroup; 
			pAccountModule.base_methods["reqDelCardGroup"] = pAccount_reqDelCardGroup;

			pAccountModule.idbase_methods[pAccount_reqDelCardGroup.methodUtype] = pAccount_reqDelCardGroup;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqDelCardGroup / 6).");

			List<DATATYPE_BASE> pAccount_reqEditCardGroup_args = new List<DATATYPE_BASE>();
			pAccount_reqEditCardGroup_args.Add(EntityDef.id2datatypes[25]);

			Method pAccount_reqEditCardGroup = new Method();
			pAccount_reqEditCardGroup.name = "reqEditCardGroup";
			pAccount_reqEditCardGroup.methodUtype = 5;
			pAccount_reqEditCardGroup.aliasID = -1;
			pAccount_reqEditCardGroup.args = pAccount_reqEditCardGroup_args;

			pAccountModule.methods["reqEditCardGroup"] = pAccount_reqEditCardGroup; 
			pAccountModule.base_methods["reqEditCardGroup"] = pAccount_reqEditCardGroup;

			pAccountModule.idbase_methods[pAccount_reqEditCardGroup.methodUtype] = pAccount_reqEditCardGroup;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqEditCardGroup / 5).");

			List<DATATYPE_BASE> pAccount_reqOpenKabao_args = new List<DATATYPE_BASE>();

			Method pAccount_reqOpenKabao = new Method();
			pAccount_reqOpenKabao.name = "reqOpenKabao";
			pAccount_reqOpenKabao.methodUtype = 4;
			pAccount_reqOpenKabao.aliasID = -1;
			pAccount_reqOpenKabao.args = pAccount_reqOpenKabao_args;

			pAccountModule.methods["reqOpenKabao"] = pAccount_reqOpenKabao; 
			pAccountModule.base_methods["reqOpenKabao"] = pAccount_reqOpenKabao;

			pAccountModule.idbase_methods[pAccount_reqOpenKabao.methodUtype] = pAccount_reqOpenKabao;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqOpenKabao / 4).");

		}

		public static void initDefTypes()
		{
			{
				UInt16 utype = 2;
				string typeName = "UINT8";
				string name = "UINT8";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 3;
				string typeName = "UINT16";
				string name = "UINT16";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 5;
				string typeName = "UID";
				string name = "UINT64";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 4;
				string typeName = "UINT32";
				string name = "UINT32";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 6;
				string typeName = "INT8";
				string name = "INT8";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 7;
				string typeName = "INT16";
				string name = "INT16";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 8;
				string typeName = "INT32";
				string name = "INT32";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 9;
				string typeName = "INT64";
				string name = "INT64";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 1;
				string typeName = "STRING";
				string name = "STRING";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 12;
				string typeName = "UNICODE";
				string name = "UNICODE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 13;
				string typeName = "FLOAT";
				string name = "FLOAT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 14;
				string typeName = "DOUBLE";
				string name = "DOUBLE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PYTHON";
				string name = "PYTHON";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_DICT";
				string name = "PY_DICT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_TUPLE";
				string name = "PY_TUPLE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_LIST";
				string name = "PY_LIST";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "ENTITYCALL";
				string name = "ENTITYCALL";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 11;
				string typeName = "BLOB";
				string name = "BLOB";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 15;
				string typeName = "VECTOR2";
				string name = "VECTOR2";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 16;
				string typeName = "VECTOR3";
				string name = "VECTOR3";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 17;
				string typeName = "VECTOR4";
				string name = "VECTOR4";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 22;
				string typeName = "CARD_INFO";
				DATATYPE_CARD_INFO datatype = new DATATYPE_CARD_INFO();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 23;
				string typeName = "OPEN_PACK_RUL";
				DATATYPE_OPEN_PACK_RUL datatype = new DATATYPE_OPEN_PACK_RUL();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 24;
				string typeName = "CARD_LIST";
				DATATYPE_CARD_LIST datatype = new DATATYPE_CARD_LIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 25;
				string typeName = "CARDGROUP_INFO";
				DATATYPE_CARDGROUP_INFO datatype = new DATATYPE_CARDGROUP_INFO();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 26;
				string typeName = "CARDGROUP_INFO_LIST";
				DATATYPE_CARDGROUP_INFO_LIST datatype = new DATATYPE_CARDGROUP_INFO_LIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			foreach(string datatypeStr in EntityDef.datatypes.Keys)
			{
				DATATYPE_BASE dataType = EntityDef.datatypes[datatypeStr];
				if(dataType != null)
				{
					dataType.bind();
				}
			}
		}

	}


}